services:
  - type: web
    name: athlete-api
    runtime: docker
    dockerfilePath: ./backend-fastapi/Dockerfile
    dockerContext: .
    plan: free
    envVars:
      - key: TURSO_DATABASE_URL
        sync: false
      - key: TURSO_AUTH_TOKEN
        sync: false
      - key: CORS_ORIGINS
        value: "https://athlete-app-kohl.vercel.app,http://localhost:5173"
