import { Header } from "../components/Header";
import { Card, CardContent, CardHeader, CardTitle } from "../components/ui/card";
import { Button } from "../components/ui/button";
import { Calendar, ChevronLeft, ChevronRight, ChevronDown } from "lucide-react";
import { useState, useRef, useEffect } from "react";

// ── Types ──────────────────────────────────────────────────────────────────────

interface WeeklySession {
  day: string;
  date: string;
  type: string;
  session: string;
  duration: string;
  intensity: string;
  details: string;
  color: string;
}

interface HistorialActivity {
  date: string;
  /** Label for exercises count, e.g. "4 ejercicios", or "" for runs */
  exercises: string;
  description: string;
  /** Expanded detail — provided by the data source */
  detail?: React.ReactNode;
}

export function Calendario() {
  const [currentWeek, setCurrentWeek] = useState(0);
  const [expandedActivity, setExpandedActivity] = useState<string | null>(null);
  const activityRefs = useRef<{ [key: string]: HTMLDivElement | null }>({});

  // TODO: fetch from weekly training plan (generated by Entrenador Personal)
  const weeklyPlan: WeeklySession[] = [];

  // TODO: fetch from activity history log (Garmin sync / manual entries)
  const historialActivities: HistorialActivity[] = [];

  // ── Computed summary ────────────────────────────────────────────────────────
  const totalSesiones = weeklyPlan.length;
  const totalMinutos = 0; // TODO: sum from weeklyPlan durations
  const totalRunning = weeklyPlan.filter((d) => d.type === "Running").length;
  const totalFuerza = weeklyPlan.filter((d) => d.type === "Fuerza").length;

  // ── Helpers ────────────────────────────────────────────────────────────────

  const getIntensityColor = (intensity: string) => {
    switch (intensity) {
      case "Muy Alta": return "bg-red-500/20 text-red-400 border-red-500/40";
      case "Alta": return "bg-orange-500/20 text-orange-400 border-orange-500/40";
      case "Media": return "bg-yellow-500/20 text-yellow-400 border-yellow-500/40";
      case "Baja": return "bg-green-500/20 text-green-400 border-green-500/40";
      case "Muy Baja": return "bg-blue-500/20 text-blue-400 border-blue-500/40";
      default: return "bg-[#8B949E]/20 text-[#8B949E] border-[#8B949E]/40";
    }
  };

  const getTypeIcon = (type: string) => {
    switch (type) {
      case "Running": return "🏃";
      case "Fuerza": return "💪";
      case "Recuperación": return "🧘";
      default: return "📅";
    }
  };

  useEffect(() => {
    if (expandedActivity) {
      const ref = activityRefs.current[expandedActivity];
      if (ref) {
        ref.scrollIntoView({ behavior: "smooth", block: "center" });
      }
    }
  }, [expandedActivity]);

  // ── Render ─────────────────────────────────────────────────────────────────

  return (
    <div className="min-h-screen bg-[#0E1117]">
      <Header />

      <main className="container mx-auto px-6 py-8">
        {/* Header */}
        <div className="flex items-center justify-between mb-6">
          <h2 className="text-2xl font-semibold text-white flex items-center gap-2">
            <Calendar className="h-6 w-6 text-[#C9FF00]" />
            Calendario de Entrenamiento
          </h2>

          <div className="flex items-center gap-3">
            <Button
              variant="ghost"
              size="sm"
              className="text-white hover:bg-[#30363D]"
              onClick={() => setCurrentWeek((w) => w - 1)}
            >
              <ChevronLeft className="h-4 w-4 mr-1" />
              Semana Anterior
            </Button>
            <span className="text-white font-semibold px-4">
              Semana {currentWeek === 0 ? "Actual" : currentWeek > 0 ? `+${currentWeek}` : currentWeek}
            </span>
            <Button
              variant="ghost"
              size="sm"
              className="text-white hover:bg-[#30363D]"
              onClick={() => setCurrentWeek((w) => w + 1)}
            >
              Semana Siguiente
              <ChevronRight className="h-4 w-4 ml-1" />
            </Button>
          </div>
        </div>

        {/* Vista Semanal en Tarjetas */}
        <section className="mb-8">
          <h3 className="text-lg font-semibold mb-4 text-white">Vista Semanal</h3>
          {weeklyPlan.length > 0 ? (
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 xl:grid-cols-7 gap-4">
              {weeklyPlan.map((day, index) => (
                <Card
                  key={index}
                  className={`bg-[#161B22] border ${day.color} border-l-4 rounded-xl hover:shadow-lg transition-all cursor-pointer`}
                >
                  <CardContent className="pt-4 pb-4">
                    <div className="text-center mb-3">
                      <p className="text-xs text-[#8B949E] font-semibold mb-1">{day.day}</p>
                      <p className="text-sm text-white font-bold">{day.date}</p>
                    </div>
                    <div className="text-center mb-3">
                      <p className="text-2xl mb-2">{getTypeIcon(day.type)}</p>
                      <p className="text-xs text-[#8B949E] mb-1">{day.type}</p>
                      <p className="text-sm text-[#C9FF00] font-semibold">{day.session}</p>
                    </div>
                    <div className="space-y-2">
                      <div className="flex items-center justify-between text-xs">
                        <span className="text-[#8B949E]">Duración:</span>
                        <span className="text-white font-semibold">{day.duration}</span>
                      </div>
                      <div className="flex items-center justify-center">
                        <span
                          className={`px-2 py-1 rounded-full text-xs font-semibold border ${getIntensityColor(day.intensity)}`}
                        >
                          {day.intensity}
                        </span>
                      </div>
                    </div>
                  </CardContent>
                </Card>
              ))}
            </div>
          ) : (
            <Card className="bg-[#161B22] border border-[#C9FF00]/20 rounded-xl">
              <CardContent className="pt-8 pb-8 text-center">
                <Calendar className="h-10 w-10 text-[#30363D] mx-auto mb-3" />
                <p className="text-[#8B949E] text-sm">No hay plan para esta semana.</p>
                <p className="text-xs text-[#30363D] mt-1">
                  Genera uno en Entrenador Personal → Generar Plan Semanal.
                </p>
              </CardContent>
            </Card>
          )}
        </section>

        {/* Vista Detallada Tabular */}
        <section>
          <h3 className="text-lg font-semibold mb-4 text-white">Vista Detallada</h3>
          <Card className="bg-[#161B22] border border-[#C9FF00]/30 rounded-xl">
            <CardContent className="pt-6">
              {weeklyPlan.length > 0 ? (
                <div className="overflow-x-auto">
                  <table className="w-full text-left">
                    <thead>
                      <tr className="border-b border-[#C9FF00]/20">
                        <th className="text-sm font-semibold text-[#C9FF00] pb-3 px-4">Fecha</th>
                        <th className="text-sm font-semibold text-[#C9FF00] pb-3 px-4">Tipo</th>
                        <th className="text-sm font-semibold text-[#C9FF00] pb-3 px-4">Sesión</th>
                        <th className="text-sm font-semibold text-[#C9FF00] pb-3 px-4">Duración</th>
                        <th className="text-sm font-semibold text-[#C9FF00] pb-3 px-4">Intensidad</th>
                        <th className="text-sm font-semibold text-[#C9FF00] pb-3 px-4">Detalles</th>
                      </tr>
                    </thead>
                    <tbody>
                      {weeklyPlan.map((day, index) => (
                        <tr
                          key={index}
                          className="border-b border-[#30363D] hover:bg-[#0E1117] transition-colors"
                        >
                          <td className="py-4 px-4">
                            <p className="text-white font-semibold text-sm">{day.day}</p>
                            <p className="text-[#8B949E] text-xs">{day.date}</p>
                          </td>
                          <td className="py-4 px-4">
                            <div className="flex items-center gap-2">
                              <span className="text-xl">{getTypeIcon(day.type)}</span>
                              <span className="text-white text-sm">{day.type}</span>
                            </div>
                          </td>
                          <td className="py-4 px-4">
                            <p className="text-[#C9FF00] font-semibold text-sm">{day.session}</p>
                          </td>
                          <td className="py-4 px-4">
                            <p className="text-white text-sm">{day.duration}</p>
                          </td>
                          <td className="py-4 px-4">
                            <span
                              className={`px-3 py-1 rounded-full text-xs font-semibold border ${getIntensityColor(day.intensity)}`}
                            >
                              {day.intensity}
                            </span>
                          </td>
                          <td className="py-4 px-4 max-w-md">
                            <p className="text-[#8B949E] text-xs leading-relaxed">{day.details}</p>
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              ) : (
                <div className="py-8 text-center text-[#8B949E] text-sm">
                  Sin sesiones para mostrar esta semana.
                </div>
              )}

              {/* Resumen semanal */}
              <div className="mt-6 pt-6 border-t border-[#C9FF00]/20">
                <h4 className="text-sm font-semibold text-white mb-4">Resumen de la Semana</h4>
                <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
                  <div className="bg-[#0E1117] rounded-lg p-4 text-center">
                    <p className="text-xs text-[#8B949E] mb-1">Total Sesiones</p>
                    <p className="text-2xl font-bold text-white">{totalSesiones}</p>
                  </div>
                  <div className="bg-[#0E1117] rounded-lg p-4 text-center">
                    <p className="text-xs text-[#8B949E] mb-1">Tiempo Total</p>
                    <p className="text-2xl font-bold text-white">
                      {totalMinutos > 0 ? `${Math.floor(totalMinutos / 60)}h ${totalMinutos % 60}min` : "--"}
                    </p>
                  </div>
                  <div className="bg-[#0E1117] rounded-lg p-4 text-center">
                    <p className="text-xs text-[#8B949E] mb-1">Running</p>
                    <p className="text-2xl font-bold text-[#C9FF00]">{totalRunning}</p>
                  </div>
                  <div className="bg-[#0E1117] rounded-lg p-4 text-center">
                    <p className="text-xs text-[#8B949E] mb-1">Fuerza</p>
                    <p className="text-2xl font-bold text-purple-400">{totalFuerza}</p>
                  </div>
                </div>
              </div>
            </CardContent>
          </Card>
        </section>

        {/* Historial por entrenamientos */}
        <section className="mt-8">
          <h3 className="text-lg font-semibold mb-4 text-white">Historial por Entrenamientos</h3>
          {historialActivities.length > 0 ? (
            <div className="space-y-3">
              {historialActivities.map((activity, index) => {
                const activityKey = activity.date;
                const isExpanded = expandedActivity === activityKey;

                return (
                  <div
                    key={index}
                    ref={(el) => (activityRefs.current[activityKey] = el)}
                    className="bg-[#161B22] border border-[#C9FF00]/20 rounded-xl overflow-hidden"
                  >
                    <button
                      onClick={() => setExpandedActivity(isExpanded ? null : activityKey)}
                      className="w-full flex items-center justify-between px-5 py-4 hover:bg-[#1a2130] transition-colors"
                    >
                      <div className="flex items-center gap-3 text-left">
                        <ChevronDown
                          className={`h-4 w-4 transition-transform ${
                            isExpanded ? "text-[#C9FF00] rotate-180" : "text-[#8B949E]"
                          }`}
                        />
                        <span className="text-white font-semibold">
                          {activity.date} · {activity.exercises || "Carrera"} · {activity.description}
                        </span>
                      </div>
                    </button>

                    {isExpanded && (
                      <div className="px-5 pb-5 border-t border-[#C9FF00]/10">
                        <div className="mt-4 bg-[#0E1117] rounded-lg p-4">
                          {activity.detail ?? (
                            <p className="text-[#8B949E] text-sm">
                              Sin detalles adicionales para esta sesión.
                            </p>
                          )}
                        </div>
                      </div>
                    )}
                  </div>
                );
              })}
            </div>
          ) : (
            <Card className="bg-[#161B22] border border-[#C9FF00]/20 rounded-xl">
              <CardContent className="pt-8 pb-8 text-center">
                <Calendar className="h-10 w-10 text-[#30363D] mx-auto mb-3" />
                <p className="text-[#8B949E] text-sm">Sin historial de entrenamientos.</p>
                <p className="text-xs text-[#30363D] mt-1">
                  Sincroniza tus actividades Garmin para ver el historial.
                </p>
              </CardContent>
            </Card>
          )}
        </section>
      </main>
    </div>
  );
}
