-- Migration: atleta.db -> Turso
-- Generated automatically

-- usuarios (2 rows)
INSERT OR REPLACE INTO usuarios (id, nombre, edad, genero, peso, objetivo, carrera, fuerza, nivel, ritmo, email_garmin, password_garmin, password_garmin_enc, rol, fecha_objetivo, objetivo_tipo) VALUES (1, 'Malena', 21, 'Mujer', 55.0, 'Maraton', NULL, NULL, NULL, '4:00-5:00', 'malena.lozanoalonso@gmail.com', NULL, 'gAAAAABp0mFNhQg2j6Hbd-0KDrPDGDME-VqieX6mnV816Yak-9hzyR0mpas9TnDahciu4r50a5SlPHDabtgX_PjvgyDp_XqbmQ==', NULL, '2027-02-21', 'maraton');
INSERT OR REPLACE INTO usuarios (id, nombre, edad, genero, peso, objetivo, carrera, fuerza, nivel, ritmo, email_garmin, password_garmin, password_garmin_enc, rol, fecha_objetivo, objetivo_tipo) VALUES (2, 'Dani', 22, 'Hombre', 70.0, 'Ultramaraton', 1, 1, NULL, NULL, NULL, NULL, NULL, NULL, '2026-09-19', 'ultramaraton');

-- actividades_garmin (27 rows)
INSERT OR REPLACE INTO actividades_garmin (id_actividad, usuario_id, fecha, tipo_deporte, distancia_m, tiempo_seg, ritmo_medio, fc_media, fc_max, potencia_media_w, cadencia_media, longitud_zancada_m, tiempo_contacto_ms, oscilacion_vertical_cm, calorias, training_effect_aerobico, training_effect_anaerobico) VALUES ('21947807316', 1, '2026-02-22 10:11:26', 'running', 5015.2900390625, 1796.3499755859375, 5.9694363669335875, 166, 186, 226.0, 164.15625, 101.02000122070314, 263.6000061035156, 9.469999694824219, NULL, NULL, NULL);
INSERT OR REPLACE INTO actividades_garmin (id_actividad, usuario_id, fecha, tipo_deporte, distancia_m, tiempo_seg, ritmo_medio, fc_media, fc_max, potencia_media_w, cadencia_media, longitud_zancada_m, tiempo_contacto_ms, oscilacion_vertical_cm, calorias, training_effect_aerobico, training_effect_anaerobico) VALUES ('22218696037', 1, '2026-03-18 17:49:06', 'strength_training', 0.0, 2688.639892578125, NULL, 124, 175, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO actividades_garmin (id_actividad, usuario_id, fecha, tipo_deporte, distancia_m, tiempo_seg, ritmo_medio, fc_media, fc_max, potencia_media_w, cadencia_media, longitud_zancada_m, tiempo_contacto_ms, oscilacion_vertical_cm, calorias, training_effect_aerobico, training_effect_anaerobico) VALUES ('22201378453', 1, '2026-03-17 10:59:38', 'indoor_cycling', 0.0, 3601.1240234375, NULL, 132, 160, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO actividades_garmin (id_actividad, usuario_id, fecha, tipo_deporte, distancia_m, tiempo_seg, ritmo_medio, fc_media, fc_max, potencia_media_w, cadencia_media, longitud_zancada_m, tiempo_contacto_ms, oscilacion_vertical_cm, calorias, training_effect_aerobico, training_effect_anaerobico) VALUES ('22192836709', 1, '2026-03-16 12:21:22', 'strength_training', 0.0, 3460.3720703125, NULL, 128, 179, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO actividades_garmin (id_actividad, usuario_id, fecha, tipo_deporte, distancia_m, tiempo_seg, ritmo_medio, fc_media, fc_max, potencia_media_w, cadencia_media, longitud_zancada_m, tiempo_contacto_ms, oscilacion_vertical_cm, calorias, training_effect_aerobico, training_effect_anaerobico) VALUES ('22185294112', 1, '2026-03-15 18:19:49', 'virtual_ride', 336.260009765625, 2701.587890625, 134.40860434720554, 139, 158, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO actividades_garmin (id_actividad, usuario_id, fecha, tipo_deporte, distancia_m, tiempo_seg, ritmo_medio, fc_media, fc_max, potencia_media_w, cadencia_media, longitud_zancada_m, tiempo_contacto_ms, oscilacion_vertical_cm, calorias, training_effect_aerobico, training_effect_anaerobico) VALUES ('22183211401', 1, '2026-03-13 18:11:41', 'strength_training', 0.0, 1234.27294921875, NULL, 95, 131, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO actividades_garmin (id_actividad, usuario_id, fecha, tipo_deporte, distancia_m, tiempo_seg, ritmo_medio, fc_media, fc_max, potencia_media_w, cadencia_media, longitud_zancada_m, tiempo_contacto_ms, oscilacion_vertical_cm, calorias, training_effect_aerobico, training_effect_anaerobico) VALUES ('22141801513', 1, '2026-03-11 18:16:30', 'strength_training', 0.0, 3231.241943359375, NULL, 108, 161, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO actividades_garmin (id_actividad, usuario_id, fecha, tipo_deporte, distancia_m, tiempo_seg, ritmo_medio, fc_media, fc_max, potencia_media_w, cadencia_media, longitud_zancada_m, tiempo_contacto_ms, oscilacion_vertical_cm, calorias, training_effect_aerobico, training_effect_anaerobico) VALUES ('22124104130', 1, '2026-03-10 10:47:56', 'running', 4251.83984375, 1521.052001953125, 5.963029056072863, 171, 186, 234.0, 158.453125, 106.45999755859376, 267.29998779296875, 9.930000305175781, NULL, NULL, NULL);
INSERT OR REPLACE INTO actividades_garmin (id_actividad, usuario_id, fecha, tipo_deporte, distancia_m, tiempo_seg, ritmo_medio, fc_media, fc_max, potencia_media_w, cadencia_media, longitud_zancada_m, tiempo_contacto_ms, oscilacion_vertical_cm, calorias, training_effect_aerobico, training_effect_anaerobico) VALUES ('22123667701', 1, '2026-03-09 18:38:10', 'strength_training', 0.0, 6814.76416015625, NULL, 128, 172, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO actividades_garmin (id_actividad, usuario_id, fecha, tipo_deporte, distancia_m, tiempo_seg, ritmo_medio, fc_media, fc_max, potencia_media_w, cadencia_media, longitud_zancada_m, tiempo_contacto_ms, oscilacion_vertical_cm, calorias, training_effect_aerobico, training_effect_anaerobico) VALUES ('22091405448', 1, '2026-03-07 11:53:16', 'running', 10008.419921875, 3798.330078125, 6.325110712329269, 171, 194, 214.0, 164.046875, 96.17999877929688, 269.6000061035156, 9.330000305175782, NULL, NULL, NULL);
INSERT OR REPLACE INTO actividades_garmin (id_actividad, usuario_id, fecha, tipo_deporte, distancia_m, tiempo_seg, ritmo_medio, fc_media, fc_max, potencia_media_w, cadencia_media, longitud_zancada_m, tiempo_contacto_ms, oscilacion_vertical_cm, calorias, training_effect_aerobico, training_effect_anaerobico) VALUES ('22084322917', 1, '2026-03-06 18:38:12', 'strength_training', 0.0, 3400.570068359375, NULL, 126, 171, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO actividades_garmin (id_actividad, usuario_id, fecha, tipo_deporte, distancia_m, tiempo_seg, ritmo_medio, fc_media, fc_max, potencia_media_w, cadencia_media, longitud_zancada_m, tiempo_contacto_ms, oscilacion_vertical_cm, calorias, training_effect_aerobico, training_effect_anaerobico) VALUES ('22069676089', 1, '2026-03-05 12:49:29', 'strength_training', 0.0, 3163.156982421875, NULL, 106, 148, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO actividades_garmin (id_actividad, usuario_id, fecha, tipo_deporte, distancia_m, tiempo_seg, ritmo_medio, fc_media, fc_max, potencia_media_w, cadencia_media, longitud_zancada_m, tiempo_contacto_ms, oscilacion_vertical_cm, calorias, training_effect_aerobico, training_effect_anaerobico) VALUES ('22063058191', 1, '2026-03-04 18:13:34', 'pilates', 0.0, 7438.3779296875, NULL, 81, 129, NULL, NULL, 0.0, NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO actividades_garmin (id_actividad, usuario_id, fecha, tipo_deporte, distancia_m, tiempo_seg, ritmo_medio, fc_media, fc_max, potencia_media_w, cadencia_media, longitud_zancada_m, tiempo_contacto_ms, oscilacion_vertical_cm, calorias, training_effect_aerobico, training_effect_anaerobico) VALUES ('22051512274', 1, '2026-03-03 19:56:19', 'strength_training', 0.0, 4345.04296875, NULL, 78, 159, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO actividades_garmin (id_actividad, usuario_id, fecha, tipo_deporte, distancia_m, tiempo_seg, ritmo_medio, fc_media, fc_max, potencia_media_w, cadencia_media, longitud_zancada_m, tiempo_contacto_ms, oscilacion_vertical_cm, calorias, training_effect_aerobico, training_effect_anaerobico) VALUES ('22046997366', 1, '2026-03-03 12:47:14', 'multi_sport', 4000.0, 1740.759, 6.976966826124671, NULL, 175, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO actividades_garmin (id_actividad, usuario_id, fecha, tipo_deporte, distancia_m, tiempo_seg, ritmo_medio, fc_media, fc_max, potencia_media_w, cadencia_media, longitud_zancada_m, tiempo_contacto_ms, oscilacion_vertical_cm, calorias, training_effect_aerobico, training_effect_anaerobico) VALUES ('22039450109', 1, '2026-03-02 18:39:25', 'strength_training', 0.0, 3939.323974609375, NULL, 105, 170, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO actividades_garmin (id_actividad, usuario_id, fecha, tipo_deporte, distancia_m, tiempo_seg, ritmo_medio, fc_media, fc_max, potencia_media_w, cadencia_media, longitud_zancada_m, tiempo_contacto_ms, oscilacion_vertical_cm, calorias, training_effect_aerobico, training_effect_anaerobico) VALUES ('22011903955', 1, '2026-02-28 11:43:39', 'hiit', 0.0, 432.3800048828125, NULL, 130, 165, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO actividades_garmin (id_actividad, usuario_id, fecha, tipo_deporte, distancia_m, tiempo_seg, ritmo_medio, fc_media, fc_max, potencia_media_w, cadencia_media, longitud_zancada_m, tiempo_contacto_ms, oscilacion_vertical_cm, calorias, training_effect_aerobico, training_effect_anaerobico) VALUES ('22011680733', 1, '2026-02-28 11:05:58', 'running', 2534.3798828125, 1114.35205078125, 7.3292291925700495, 163, 197, 194.0, 146.859375, 97.27000122070314, 269.20001220703125, 8.490000152587891, NULL, NULL, NULL);
INSERT OR REPLACE INTO actividades_garmin (id_actividad, usuario_id, fecha, tipo_deporte, distancia_m, tiempo_seg, ritmo_medio, fc_media, fc_max, potencia_media_w, cadencia_media, longitud_zancada_m, tiempo_contacto_ms, oscilacion_vertical_cm, calorias, training_effect_aerobico, training_effect_anaerobico) VALUES ('21978556412', 1, '2026-02-25 10:06:34', 'running', 3152.8798828125, 1066.8759765625, 5.640158070042835, 164, 181, 237.0, 164.609375, 107.64000244140625, 259.0, 9.8, NULL, NULL, NULL);
INSERT OR REPLACE INTO actividades_garmin (id_actividad, usuario_id, fecha, tipo_deporte, distancia_m, tiempo_seg, ritmo_medio, fc_media, fc_max, potencia_media_w, cadencia_media, longitud_zancada_m, tiempo_contacto_ms, oscilacion_vertical_cm, calorias, training_effect_aerobico, training_effect_anaerobico) VALUES ('21972344616', 1, '2026-02-24 17:27:41', 'bouldering', 0.0, 4913.2177734375, NULL, 98, 172, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO actividades_garmin (id_actividad, usuario_id, fecha, tipo_deporte, distancia_m, tiempo_seg, ritmo_medio, fc_media, fc_max, potencia_media_w, cadencia_media, longitud_zancada_m, tiempo_contacto_ms, oscilacion_vertical_cm, calorias, training_effect_aerobico, training_effect_anaerobico) VALUES ('21961462933', 1, '2026-02-23 18:10:18', 'multi_sport', 0.0, 4170.4329833984375, NULL, NULL, 167, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO actividades_garmin (id_actividad, usuario_id, fecha, tipo_deporte, distancia_m, tiempo_seg, ritmo_medio, fc_media, fc_max, potencia_media_w, cadencia_media, longitud_zancada_m, tiempo_contacto_ms, oscilacion_vertical_cm, calorias, training_effect_aerobico, training_effect_anaerobico) VALUES ('22341699207', 1, '2026-03-29 18:57:08', 'indoor_cycling', NULL, 3603.639892578125, NULL, 128, 162, NULL, NULL, NULL, NULL, NULL, 317.0, NULL, NULL);
INSERT OR REPLACE INTO actividades_garmin (id_actividad, usuario_id, fecha, tipo_deporte, distancia_m, tiempo_seg, ritmo_medio, fc_media, fc_max, potencia_media_w, cadencia_media, longitud_zancada_m, tiempo_contacto_ms, oscilacion_vertical_cm, calorias, training_effect_aerobico, training_effect_anaerobico) VALUES ('22340518746', 1, '2026-03-29 17:10:04', 'indoor_climbing', NULL, 3527.384033203125, NULL, 116, 179, NULL, NULL, NULL, NULL, NULL, 264.0, NULL, NULL);
INSERT OR REPLACE INTO actividades_garmin (id_actividad, usuario_id, fecha, tipo_deporte, distancia_m, tiempo_seg, ritmo_medio, fc_media, fc_max, potencia_media_w, cadencia_media, longitud_zancada_m, tiempo_contacto_ms, oscilacion_vertical_cm, calorias, training_effect_aerobico, training_effect_anaerobico) VALUES ('22417525116', 1, '2026-04-05 16:17:57', 'indoor_cycling', NULL, 2065.451904296875, NULL, 128, 144, NULL, NULL, NULL, NULL, NULL, 195.0, NULL, NULL);
INSERT OR REPLACE INTO actividades_garmin (id_actividad, usuario_id, fecha, tipo_deporte, distancia_m, tiempo_seg, ritmo_medio, fc_media, fc_max, potencia_media_w, cadencia_media, longitud_zancada_m, tiempo_contacto_ms, oscilacion_vertical_cm, calorias, training_effect_aerobico, training_effect_anaerobico) VALUES ('22390722086', 1, '2026-04-03 08:16:15', 'running', 3717.639892578125, 2137.449951171875, 9.58, 121, 152, 118.0, 129.15625, 78.29000244140626, 387.3999938964844, 7.20999984741211, 189.0, 1.899999976158142, 0.0);
INSERT OR REPLACE INTO actividades_garmin (id_actividad, usuario_id, fecha, tipo_deporte, distancia_m, tiempo_seg, ritmo_medio, fc_media, fc_max, potencia_media_w, cadencia_media, longitud_zancada_m, tiempo_contacto_ms, oscilacion_vertical_cm, calorias, training_effect_aerobico, training_effect_anaerobico) VALUES ('22357428308', 1, '2026-03-31 09:55:29', 'strength_training', NULL, 4098.65380859375, NULL, 117, 161, NULL, NULL, NULL, NULL, NULL, 292.0, NULL, NULL);
INSERT OR REPLACE INTO actividades_garmin (id_actividad, usuario_id, fecha, tipo_deporte, distancia_m, tiempo_seg, ritmo_medio, fc_media, fc_max, potencia_media_w, cadencia_media, longitud_zancada_m, tiempo_contacto_ms, oscilacion_vertical_cm, calorias, training_effect_aerobico, training_effect_anaerobico) VALUES ('22349776357', 1, '2026-03-30 16:21:03', 'strength_training', NULL, 3933.7880859375, NULL, 114, 176, NULL, NULL, NULL, NULL, NULL, 272.0, NULL, NULL);

-- diario_fisiologia (22 rows)
INSERT OR REPLACE INTO diario_fisiologia (id, usuario_id, fecha, fase_ciclo, fatiga_subjetiva, dolor_notas, sangre, sintomas, estado_animo, feedback_entreno) VALUES (1, 1, '2026-03-19', 'Menstruación', NULL, '', 'Manchado', '', 'Normal', 'Regulero');
INSERT OR REPLACE INTO diario_fisiologia (id, usuario_id, fecha, fase_ciclo, fatiga_subjetiva, dolor_notas, sangre, sintomas, estado_animo, feedback_entreno) VALUES (2, 1, '2026-03-20', 'Lútea', NULL, 'Dolor de senos', NULL, 'Dolor de senos', 'Cansada', 'Regulero');
INSERT OR REPLACE INTO diario_fisiologia (id, usuario_id, fecha, fase_ciclo, fatiga_subjetiva, dolor_notas, sangre, sintomas, estado_animo, feedback_entreno) VALUES (3, 1, '2026-04-05', 'Menstruación', NULL, '', 'Manchado', '', 'Normal', 'Regulero');
INSERT OR REPLACE INTO diario_fisiologia (id, usuario_id, fecha, fase_ciclo, fatiga_subjetiva, dolor_notas, sangre, sintomas, estado_animo, feedback_entreno) VALUES (4, 1, '2026-04-05', 'Menstruación', NULL, '', 'Fuerte', '', 'Normal', 'Regulero');
INSERT OR REPLACE INTO diario_fisiologia (id, usuario_id, fecha, fase_ciclo, fatiga_subjetiva, dolor_notas, sangre, sintomas, estado_animo, feedback_entreno) VALUES (5, 1, '2026-04-05', 'Menstruación', NULL, '', 'Manchado', '', 'Normal', 'Regulero');
INSERT OR REPLACE INTO diario_fisiologia (id, usuario_id, fecha, fase_ciclo, fatiga_subjetiva, dolor_notas, sangre, sintomas, estado_animo, feedback_entreno) VALUES (6, 1, '2026-04-05', 'Menstruación', NULL, '', NULL, '', 'Normal', 'A tope');
INSERT OR REPLACE INTO diario_fisiologia (id, usuario_id, fecha, fase_ciclo, fatiga_subjetiva, dolor_notas, sangre, sintomas, estado_animo, feedback_entreno) VALUES (7, 1, '2026-04-06', 'Menstruación', NULL, '', 'Manchado', '', 'Normal', 'A tope');
INSERT OR REPLACE INTO diario_fisiologia (id, usuario_id, fecha, fase_ciclo, fatiga_subjetiva, dolor_notas, sangre, sintomas, estado_animo, feedback_entreno) VALUES (8, 1, '2026-04-06', 'Menstruación', NULL, '', 'Manchado', '', 'Normal', 'Regulero');
INSERT OR REPLACE INTO diario_fisiologia (id, usuario_id, fecha, fase_ciclo, fatiga_subjetiva, dolor_notas, sangre, sintomas, estado_animo, feedback_entreno) VALUES (9, 1, '2026-04-06', 'Lútea', NULL, '', 'Manchado', '', 'Normal', '');
INSERT OR REPLACE INTO diario_fisiologia (id, usuario_id, fecha, fase_ciclo, fatiga_subjetiva, dolor_notas, sangre, sintomas, estado_animo, feedback_entreno) VALUES (10, 1, '2026-04-06', 'Menstruación', NULL, '', NULL, '', 'Normal', '');
INSERT OR REPLACE INTO diario_fisiologia (id, usuario_id, fecha, fase_ciclo, fatiga_subjetiva, dolor_notas, sangre, sintomas, estado_animo, feedback_entreno) VALUES (11, 1, '2026-04-06', 'Lútea', NULL, '', 'Manchado', '', 'Normal', '');
INSERT OR REPLACE INTO diario_fisiologia (id, usuario_id, fecha, fase_ciclo, fatiga_subjetiva, dolor_notas, sangre, sintomas, estado_animo, feedback_entreno) VALUES (12, 1, '2026-04-19', 'Ovulación', NULL, '', NULL, '', 'Normal', '');
INSERT OR REPLACE INTO diario_fisiologia (id, usuario_id, fecha, fase_ciclo, fatiga_subjetiva, dolor_notas, sangre, sintomas, estado_animo, feedback_entreno) VALUES (13, 1, '2026-03-19', 'Menstruación', NULL, '', NULL, '', 'Normal', 'Regulero');
INSERT OR REPLACE INTO diario_fisiologia (id, usuario_id, fecha, fase_ciclo, fatiga_subjetiva, dolor_notas, sangre, sintomas, estado_animo, feedback_entreno) VALUES (14, 1, '2026-03-25', 'Menstruación', NULL, '', 'Ligero', '', 'Normal', 'Regulero');
INSERT OR REPLACE INTO diario_fisiologia (id, usuario_id, fecha, fase_ciclo, fatiga_subjetiva, dolor_notas, sangre, sintomas, estado_animo, feedback_entreno) VALUES (15, 1, '2026-03-26', 'Menstruación', NULL, '', 'Medio', '', 'Normal', 'Regulero');
INSERT OR REPLACE INTO diario_fisiologia (id, usuario_id, fecha, fase_ciclo, fatiga_subjetiva, dolor_notas, sangre, sintomas, estado_animo, feedback_entreno) VALUES (16, 1, '2026-03-27', 'Menstruación', NULL, '', 'Medio', '', 'Normal', '');
INSERT OR REPLACE INTO diario_fisiologia (id, usuario_id, fecha, fase_ciclo, fatiga_subjetiva, dolor_notas, sangre, sintomas, estado_animo, feedback_entreno) VALUES (17, 1, '2026-03-26', 'Menstruación', NULL, '', 'Medio', '', 'Normal', '');
INSERT OR REPLACE INTO diario_fisiologia (id, usuario_id, fecha, fase_ciclo, fatiga_subjetiva, dolor_notas, sangre, sintomas, estado_animo, feedback_entreno) VALUES (18, 1, '2026-03-25', 'Menstruación', NULL, '', 'Ligero', '', 'Normal', '');
INSERT OR REPLACE INTO diario_fisiologia (id, usuario_id, fecha, fase_ciclo, fatiga_subjetiva, dolor_notas, sangre, sintomas, estado_animo, feedback_entreno) VALUES (19, 1, '2026-03-28', 'Menstruación', NULL, '', 'Ligero', '', 'Normal', '');
INSERT OR REPLACE INTO diario_fisiologia (id, usuario_id, fecha, fase_ciclo, fatiga_subjetiva, dolor_notas, sangre, sintomas, estado_animo, feedback_entreno) VALUES (20, 1, '2026-03-29', 'Menstruación', NULL, '', 'Ligero', '', 'Normal', '');
INSERT OR REPLACE INTO diario_fisiologia (id, usuario_id, fecha, fase_ciclo, fatiga_subjetiva, dolor_notas, sangre, sintomas, estado_animo, feedback_entreno) VALUES (21, 1, '2026-04-06', 'Menstruación', NULL, '', NULL, '', 'Normal', '');
INSERT OR REPLACE INTO diario_fisiologia (id, usuario_id, fecha, fase_ciclo, fatiga_subjetiva, dolor_notas, sangre, sintomas, estado_animo, feedback_entreno) VALUES (22, 1, '2026-04-06', 'Ovulación', NULL, '', NULL, '', 'Normal', '');

-- plan_entrenamiento (7 rows)
INSERT OR REPLACE INTO plan_entrenamiento (id, usuario_id, semana_inicio, fecha, tipo, sesion, detalles, duracion_min, intensidad, creado_en) VALUES (15, 1, '2026-04-06', '2026-04-06', 'Fuerza', 'Sesión de fuerza 60 min. Sigue el plan de ejercicios de la semana.', NULL, 60, 'Media', '2026-04-06 15:08:53');
INSERT OR REPLACE INTO plan_entrenamiento (id, usuario_id, semana_inicio, fecha, tipo, sesion, detalles, duracion_min, intensidad, creado_en) VALUES (16, 1, '2026-04-06', '2026-04-07', 'Carrera Z2 + 5min drills técnica (cadencia)', 'Sesión de Carrera Z2 + 5min drills técnica (cadencia) — 5 km. Ejecuta según tus sensaciones del día.', NULL, 32, 'Baja', '2026-04-06 15:08:53');
INSERT OR REPLACE INTO plan_entrenamiento (id, usuario_id, semana_inicio, fecha, tipo, sesion, detalles, duracion_min, intensidad, creado_en) VALUES (17, 1, '2026-04-06', '2026-04-08', 'Fuerza', 'Sesión de fuerza 60 min. Sigue el plan de ejercicios de la semana.', NULL, 60, 'Media', '2026-04-06 15:08:53');
INSERT OR REPLACE INTO plan_entrenamiento (id, usuario_id, semana_inicio, fecha, tipo, sesion, detalles, duracion_min, intensidad, creado_en) VALUES (18, 1, '2026-04-06', '2026-04-09', 'Progresiva', 'Carrera progresiva 6 km. Empieza suave y termina en zona 4.', NULL, 33, 'Media-Alta', '2026-04-06 15:08:53');
INSERT OR REPLACE INTO plan_entrenamiento (id, usuario_id, semana_inicio, fecha, tipo, sesion, detalles, duracion_min, intensidad, creado_en) VALUES (19, 1, '2026-04-06', '2026-04-10', 'Fuerza', 'Sesión de fuerza 60 min. Sigue el plan de ejercicios de la semana.', NULL, 60, 'Media', '2026-04-06 15:08:53');
INSERT OR REPLACE INTO plan_entrenamiento (id, usuario_id, semana_inicio, fecha, tipo, sesion, detalles, duracion_min, intensidad, creado_en) VALUES (20, 1, '2026-04-06', '2026-04-11', 'Tirada Larga', 'Carrera larga 6.0 km en Z2. Mantén conversación, no te pases de ritmo.', NULL, 39, 'Baja', '2026-04-06 15:08:53');
INSERT OR REPLACE INTO plan_entrenamiento (id, usuario_id, semana_inicio, fecha, tipo, sesion, detalles, duracion_min, intensidad, creado_en) VALUES (21, 1, '2026-04-06', '2026-04-12', 'Regenerativo', 'Rodaje suave 2.0 km a baja intensidad para recuperar activamente.', NULL, 15, 'Muy baja', '2026-04-06 15:08:53');

-- sesiones_fuerza (4 rows)
INSERT OR REPLACE INTO sesiones_fuerza (id, usuario_id, fecha, nota_original, resumen, created_at, tipo_registro, actividad_garmin_id, nota_estado, lesion_flag) VALUES (4, 1, '2026-03-31', 'Martes 30
HipTrust 3x8 30kg
Búlgaras 3x8 14kg sin terminar', '2 ejercicios · Glúteo, Tren Inferior', '2026-04-05 16:36:39', 'fuerza', '22357428308', '', 0);
INSERT OR REPLACE INTO sesiones_fuerza (id, usuario_id, fecha, nota_original, resumen, created_at, tipo_registro, actividad_garmin_id, nota_estado, lesion_flag) VALUES (5, 1, '2026-03-30', '30 de marzo
-dominadas 3x8- sola 2 asistidas
Remo 3x8 27kg- sin terminar
Abdominales en cable 3x8 45kg
Curl Martillo 3x6 27kg
Abdominales colgada 3x6', '5 ejercicios · Bíceps, Core, Espalda', '2026-04-06 12:27:18', 'fuerza', '22349776357', '', 0);
INSERT OR REPLACE INTO sesiones_fuerza (id, usuario_id, fecha, nota_original, resumen, created_at, tipo_registro, actividad_garmin_id, nota_estado, lesion_flag) VALUES (6, 1, '2026-03-27', '27 de marzo
-dominadas 3x8 -sola 2 asistidas
Remo 3x8 27kg- sin terminar 
Abdominales en cable 3x8 45kg
Curl Martillo 3x6 27kg
Abdominales colgada 3x6', '5 ejercicios · Core, Espalda, Bíceps', '2026-04-06 12:32:20', 'fuerza', NULL, '', 0);
INSERT OR REPLACE INTO sesiones_fuerza (id, usuario_id, fecha, nota_original, resumen, created_at, tipo_registro, actividad_garmin_id, nota_estado, lesion_flag) VALUES (7, 1, '2026-03-30', '30 de marzo
-dominadas 3x8 -sola 2 asistidas
Remo 3x8 27kg- sin terminar 
Abdominales en cable 3x8 45kg
Curl Martillo 3x6 27kg
Abdominales colgada 3x6', '5 ejercicios · Core, Espalda, Bíceps', '2026-04-06 12:48:02', 'fuerza', '22349776357', '', 0);

-- ejercicios_fuerza (17 rows)
INSERT OR REPLACE INTO ejercicios_fuerza (id, sesion_id, ejercicio, peso, series, repeticiones, grupo_muscular, musculo_principal, rpe, sensaciones) VALUES (7, 4, 'HipTrust', 30.0, 3, 8, 'Tren Inferior', 'Gluteos/Cuadriceps/Isquios', 6, '');
INSERT OR REPLACE INTO ejercicios_fuerza (id, sesion_id, ejercicio, peso, series, repeticiones, grupo_muscular, musculo_principal, rpe, sensaciones) VALUES (8, 4, 'Búlgaras', 14.0, 3, 8, 'Glúteo', 'Cuádriceps, glúteo', 6, '');
INSERT OR REPLACE INTO ejercicios_fuerza (id, sesion_id, ejercicio, peso, series, repeticiones, grupo_muscular, musculo_principal, rpe, sensaciones) VALUES (9, 5, 'Dominadas', 0.0, 3, 8, 'Espalda', 'Espalda, bíceps', 6, 'sola 2 asistidas');
INSERT OR REPLACE INTO ejercicios_fuerza (id, sesion_id, ejercicio, peso, series, repeticiones, grupo_muscular, musculo_principal, rpe, sensaciones) VALUES (10, 5, 'Remo abierto', 27.0, 3, 8, 'Espalda', 'Dorsal ancho, trapecio, romboides y deltoides posterior.', 6, 'sin terminar');
INSERT OR REPLACE INTO ejercicios_fuerza (id, sesion_id, ejercicio, peso, series, repeticiones, grupo_muscular, musculo_principal, rpe, sensaciones) VALUES (11, 5, 'Abdominales en cable', 45.0, 3, 8, 'Core', 'Recto abdominal de arriba hacia abajo', 6, '');
INSERT OR REPLACE INTO ejercicios_fuerza (id, sesion_id, ejercicio, peso, series, repeticiones, grupo_muscular, musculo_principal, rpe, sensaciones) VALUES (12, 5, 'Curl Martillo en polea', 27.0, 3, 6, 'Bíceps', 'cabeza corta del bíceps, el braquial anterior y el braquiorradial', 6, '');
INSERT OR REPLACE INTO ejercicios_fuerza (id, sesion_id, ejercicio, peso, series, repeticiones, grupo_muscular, musculo_principal, rpe, sensaciones) VALUES (13, 5, 'Abdominales colgada', 0.0, 3, 6, 'Core', 'Recto abdominal de abajo hacia arriba', 6, '');
INSERT OR REPLACE INTO ejercicios_fuerza (id, sesion_id, ejercicio, peso, series, repeticiones, grupo_muscular, musculo_principal, rpe, sensaciones) VALUES (14, 6, 'Dominadas', 0.0, 3, 8, 'Espalda', 'Espalda, bíceps', 6, '');
INSERT OR REPLACE INTO ejercicios_fuerza (id, sesion_id, ejercicio, peso, series, repeticiones, grupo_muscular, musculo_principal, rpe, sensaciones) VALUES (15, 6, 'Remo abierto', 27.0, 3, 8, 'Espalda', 'Dorsal ancho, trapecio, romboides y deltoides posterior.', 6, 'sin terminar');
INSERT OR REPLACE INTO ejercicios_fuerza (id, sesion_id, ejercicio, peso, series, repeticiones, grupo_muscular, musculo_principal, rpe, sensaciones) VALUES (16, 6, 'Abdominales en cable', 45.0, 3, 8, 'Core', 'Recto abdominal de arriba hacia abajo', 6, '');
INSERT OR REPLACE INTO ejercicios_fuerza (id, sesion_id, ejercicio, peso, series, repeticiones, grupo_muscular, musculo_principal, rpe, sensaciones) VALUES (17, 6, 'Curl Martillo en polea', 27.0, 3, 6, 'Bíceps', 'cabeza corta del bíceps, el braquial anterior y el braquiorradial', 6, '');
INSERT OR REPLACE INTO ejercicios_fuerza (id, sesion_id, ejercicio, peso, series, repeticiones, grupo_muscular, musculo_principal, rpe, sensaciones) VALUES (18, 6, 'Abdominales colgada', 0.0, 3, 6, 'Core', 'Recto abdominal de abajo hacia arriba', 6, '');
INSERT OR REPLACE INTO ejercicios_fuerza (id, sesion_id, ejercicio, peso, series, repeticiones, grupo_muscular, musculo_principal, rpe, sensaciones) VALUES (19, 7, 'Dominadas', 0.0, 3, 8, 'Espalda', 'Espalda, bíceps', 6, '');
INSERT OR REPLACE INTO ejercicios_fuerza (id, sesion_id, ejercicio, peso, series, repeticiones, grupo_muscular, musculo_principal, rpe, sensaciones) VALUES (20, 7, 'Remo abierto', 27.0, 3, 8, 'Espalda', 'Dorsal ancho, trapecio, romboides y deltoides posterior.', 6, 'sin terminar');
INSERT OR REPLACE INTO ejercicios_fuerza (id, sesion_id, ejercicio, peso, series, repeticiones, grupo_muscular, musculo_principal, rpe, sensaciones) VALUES (21, 7, 'Abdominales en cable', 45.0, 3, 8, 'Core', 'Recto abdominal de arriba hacia abajo', 6, '');
INSERT OR REPLACE INTO ejercicios_fuerza (id, sesion_id, ejercicio, peso, series, repeticiones, grupo_muscular, musculo_principal, rpe, sensaciones) VALUES (22, 7, 'Curl Martillo en polea', 27.0, 3, 6, 'Bíceps', 'cabeza corta del bíceps, el braquial anterior y el braquiorradial', 6, '');
INSERT OR REPLACE INTO ejercicios_fuerza (id, sesion_id, ejercicio, peso, series, repeticiones, grupo_muscular, musculo_principal, rpe, sensaciones) VALUES (23, 7, 'Abdominales colgada', 0.0, 3, 6, 'Core', 'Recto abdominal de abajo hacia arriba', 6, '');

-- datos_biometricos_premium (15 rows)
INSERT OR REPLACE INTO datos_biometricos_premium (id, usuario_id, fecha, hrv_ms, fc_reposo, fc_maxima, cadencia_media, longitud_zancada_m, tiempo_contacto_ms, oscilacion_vertical_cm, sleep_score, carga_aguda, carga_cronica, estres_vital, rpe_sesion, sensacion_notas, disponibilidad_min, training_readiness, body_battery, recovery_hours, spo2, potencia_media_w, vo2max, training_status, body_battery_max, body_battery_min, estres_medio) VALUES (1, 1, '2026-03-18', 65.0, 62, 152, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 95.0, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO datos_biometricos_premium (id, usuario_id, fecha, hrv_ms, fc_reposo, fc_maxima, cadencia_media, longitud_zancada_m, tiempo_contacto_ms, oscilacion_vertical_cm, sleep_score, carga_aguda, carga_cronica, estres_vital, rpe_sesion, sensacion_notas, disponibilidad_min, training_readiness, body_battery, recovery_hours, spo2, potencia_media_w, vo2max, training_status, body_battery_max, body_battery_min, estres_medio) VALUES (2, 1, '2026-03-17', 75.0, 61, 143, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 93.0, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO datos_biometricos_premium (id, usuario_id, fecha, hrv_ms, fc_reposo, fc_maxima, cadencia_media, longitud_zancada_m, tiempo_contacto_ms, oscilacion_vertical_cm, sleep_score, carga_aguda, carga_cronica, estres_vital, rpe_sesion, sensacion_notas, disponibilidad_min, training_readiness, body_battery, recovery_hours, spo2, potencia_media_w, vo2max, training_status, body_battery_max, body_battery_min, estres_medio) VALUES (3, 1, '2026-03-16', 69.0, 58, 169, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO datos_biometricos_premium (id, usuario_id, fecha, hrv_ms, fc_reposo, fc_maxima, cadencia_media, longitud_zancada_m, tiempo_contacto_ms, oscilacion_vertical_cm, sleep_score, carga_aguda, carga_cronica, estres_vital, rpe_sesion, sensacion_notas, disponibilidad_min, training_readiness, body_battery, recovery_hours, spo2, potencia_media_w, vo2max, training_status, body_battery_max, body_battery_min, estres_medio) VALUES (4, 1, '2026-03-15', 68.0, 57, 146, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO datos_biometricos_premium (id, usuario_id, fecha, hrv_ms, fc_reposo, fc_maxima, cadencia_media, longitud_zancada_m, tiempo_contacto_ms, oscilacion_vertical_cm, sleep_score, carga_aguda, carga_cronica, estres_vital, rpe_sesion, sensacion_notas, disponibilidad_min, training_readiness, body_battery, recovery_hours, spo2, potencia_media_w, vo2max, training_status, body_battery_max, body_battery_min, estres_medio) VALUES (5, 1, '2026-03-14', 48.0, 57, 109, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO datos_biometricos_premium (id, usuario_id, fecha, hrv_ms, fc_reposo, fc_maxima, cadencia_media, longitud_zancada_m, tiempo_contacto_ms, oscilacion_vertical_cm, sleep_score, carga_aguda, carga_cronica, estres_vital, rpe_sesion, sensacion_notas, disponibilidad_min, training_readiness, body_battery, recovery_hours, spo2, potencia_media_w, vo2max, training_status, body_battery_max, body_battery_min, estres_medio) VALUES (6, 1, '2026-03-13', 81.0, 59, 105, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO datos_biometricos_premium (id, usuario_id, fecha, hrv_ms, fc_reposo, fc_maxima, cadencia_media, longitud_zancada_m, tiempo_contacto_ms, oscilacion_vertical_cm, sleep_score, carga_aguda, carga_cronica, estres_vital, rpe_sesion, sensacion_notas, disponibilidad_min, training_readiness, body_battery, recovery_hours, spo2, potencia_media_w, vo2max, training_status, body_battery_max, body_battery_min, estres_medio) VALUES (7, 1, '2026-03-12', 71.0, 59, 105, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO datos_biometricos_premium (id, usuario_id, fecha, hrv_ms, fc_reposo, fc_maxima, cadencia_media, longitud_zancada_m, tiempo_contacto_ms, oscilacion_vertical_cm, sleep_score, carga_aguda, carga_cronica, estres_vital, rpe_sesion, sensacion_notas, disponibilidad_min, training_readiness, body_battery, recovery_hours, spo2, potencia_media_w, vo2max, training_status, body_battery_max, body_battery_min, estres_medio) VALUES (17, 1, '2026-03-19', 47.0, 63, 135, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 94.0, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO datos_biometricos_premium (id, usuario_id, fecha, hrv_ms, fc_reposo, fc_maxima, cadencia_media, longitud_zancada_m, tiempo_contacto_ms, oscilacion_vertical_cm, sleep_score, carga_aguda, carga_cronica, estres_vital, rpe_sesion, sensacion_notas, disponibilidad_min, training_readiness, body_battery, recovery_hours, spo2, potencia_media_w, vo2max, training_status, body_battery_max, body_battery_min, estres_medio) VALUES (25, 1, '2026-04-03', 78.0, NULL, NULL, 129.15625, 78.29000244140626, 387.3999938964844, 7.20999984741211, 88, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 95.0, 118.0, 49.0, '4', NULL, NULL, 23);
INSERT OR REPLACE INTO datos_biometricos_premium (id, usuario_id, fecha, hrv_ms, fc_reposo, fc_maxima, cadencia_media, longitud_zancada_m, tiempo_contacto_ms, oscilacion_vertical_cm, sleep_score, carga_aguda, carga_cronica, estres_vital, rpe_sesion, sensacion_notas, disponibilidad_min, training_readiness, body_battery, recovery_hours, spo2, potencia_media_w, vo2max, training_status, body_battery_max, body_battery_min, estres_medio) VALUES (32, 1, '2026-04-06', 94.0, NULL, NULL, NULL, NULL, NULL, NULL, 84, 1.9, 1.9, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 93.0, NULL, NULL, NULL, NULL, NULL, 18);
INSERT OR REPLACE INTO datos_biometricos_premium (id, usuario_id, fecha, hrv_ms, fc_reposo, fc_maxima, cadencia_media, longitud_zancada_m, tiempo_contacto_ms, oscilacion_vertical_cm, sleep_score, carga_aguda, carga_cronica, estres_vital, rpe_sesion, sensacion_notas, disponibilidad_min, training_readiness, body_battery, recovery_hours, spo2, potencia_media_w, vo2max, training_status, body_battery_max, body_battery_min, estres_medio) VALUES (61, 1, '2026-04-05', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1.9, 1.9, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO datos_biometricos_premium (id, usuario_id, fecha, hrv_ms, fc_reposo, fc_maxima, cadencia_media, longitud_zancada_m, tiempo_contacto_ms, oscilacion_vertical_cm, sleep_score, carga_aguda, carga_cronica, estres_vital, rpe_sesion, sensacion_notas, disponibilidad_min, training_readiness, body_battery, recovery_hours, spo2, potencia_media_w, vo2max, training_status, body_battery_max, body_battery_min, estres_medio) VALUES (62, 1, '2026-04-04', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1.9, 1.9, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO datos_biometricos_premium (id, usuario_id, fecha, hrv_ms, fc_reposo, fc_maxima, cadencia_media, longitud_zancada_m, tiempo_contacto_ms, oscilacion_vertical_cm, sleep_score, carga_aguda, carga_cronica, estres_vital, rpe_sesion, sensacion_notas, disponibilidad_min, training_readiness, body_battery, recovery_hours, spo2, potencia_media_w, vo2max, training_status, body_battery_max, body_battery_min, estres_medio) VALUES (64, 1, '2026-04-02', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO datos_biometricos_premium (id, usuario_id, fecha, hrv_ms, fc_reposo, fc_maxima, cadencia_media, longitud_zancada_m, tiempo_contacto_ms, oscilacion_vertical_cm, sleep_score, carga_aguda, carga_cronica, estres_vital, rpe_sesion, sensacion_notas, disponibilidad_min, training_readiness, body_battery, recovery_hours, spo2, potencia_media_w, vo2max, training_status, body_battery_max, body_battery_min, estres_medio) VALUES (65, 1, '2026-04-01', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO datos_biometricos_premium (id, usuario_id, fecha, hrv_ms, fc_reposo, fc_maxima, cadencia_media, longitud_zancada_m, tiempo_contacto_ms, oscilacion_vertical_cm, sleep_score, carga_aguda, carga_cronica, estres_vital, rpe_sesion, sensacion_notas, disponibilidad_min, training_readiness, body_battery, recovery_hours, spo2, potencia_media_w, vo2max, training_status, body_battery_max, body_battery_min, estres_medio) VALUES (66, 1, '2026-03-31', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

-- historial_lesiones (1 rows)
INSERT OR REPLACE INTO historial_lesiones (id, usuario_id, fecha_inicio, zona, tipo, activa, notas, fecha_fin, dolor) VALUES (1, 1, '2026-03-28', 'Periostitis (Tibia)', 'registro', 0, NULL, '2026-03-28', 1);

-- datos_sueno (16 rows)
INSERT OR REPLACE INTO datos_sueno (id, usuario_id, fecha, horas_totales, score, sleep_profundo_horas, sleep_rem_horas, sleep_vigilia_horas, despertares) VALUES (1, 1, '2026-03-18', 7.52, NULL, 1.2, 0.38, 0.57, 2);
INSERT OR REPLACE INTO datos_sueno (id, usuario_id, fecha, horas_totales, score, sleep_profundo_horas, sleep_rem_horas, sleep_vigilia_horas, despertares) VALUES (2, 1, '2026-03-17', 8.98, NULL, 1.27, 1.38, 0.15, 0);
INSERT OR REPLACE INTO datos_sueno (id, usuario_id, fecha, horas_totales, score, sleep_profundo_horas, sleep_rem_horas, sleep_vigilia_horas, despertares) VALUES (3, 1, '2026-03-16', 8.93, NULL, 1.0, 2.62, 0.05, 0);
INSERT OR REPLACE INTO datos_sueno (id, usuario_id, fecha, horas_totales, score, sleep_profundo_horas, sleep_rem_horas, sleep_vigilia_horas, despertares) VALUES (4, 1, '2026-03-15', 6.92, NULL, 1.05, 0.92, 0.17, 1);
INSERT OR REPLACE INTO datos_sueno (id, usuario_id, fecha, horas_totales, score, sleep_profundo_horas, sleep_rem_horas, sleep_vigilia_horas, despertares) VALUES (5, 1, '2026-03-14', 8.25, NULL, 1.12, 1.97, 0.17, 1);
INSERT OR REPLACE INTO datos_sueno (id, usuario_id, fecha, horas_totales, score, sleep_profundo_horas, sleep_rem_horas, sleep_vigilia_horas, despertares) VALUES (6, 1, '2026-03-13', 9.62, NULL, 1.28, 2.28, 0.0, 0);
INSERT OR REPLACE INTO datos_sueno (id, usuario_id, fecha, horas_totales, score, sleep_profundo_horas, sleep_rem_horas, sleep_vigilia_horas, despertares) VALUES (7, 1, '2026-03-12', 8.5, NULL, 0.98, 1.35, 0.03, 0);
INSERT OR REPLACE INTO datos_sueno (id, usuario_id, fecha, horas_totales, score, sleep_profundo_horas, sleep_rem_horas, sleep_vigilia_horas, despertares) VALUES (15, 1, '2026-03-19', 7.52, NULL, 1.0, 0.92, 0.08, 0);
INSERT OR REPLACE INTO datos_sueno (id, usuario_id, fecha, horas_totales, score, sleep_profundo_horas, sleep_rem_horas, sleep_vigilia_horas, despertares) VALUES (25, 1, '2026-04-05', 8.58, 95, 2.05, 1.75, 0.0, NULL);
INSERT OR REPLACE INTO datos_sueno (id, usuario_id, fecha, horas_totales, score, sleep_profundo_horas, sleep_rem_horas, sleep_vigilia_horas, despertares) VALUES (26, 1, '2026-04-04', 7.98, 84, 1.1, 1.6, 0.23, 1);
INSERT OR REPLACE INTO datos_sueno (id, usuario_id, fecha, horas_totales, score, sleep_profundo_horas, sleep_rem_horas, sleep_vigilia_horas, despertares) VALUES (27, 1, '2026-04-03', 9.18, 88, 1.55, 1.55, 0.15, 0);
INSERT OR REPLACE INTO datos_sueno (id, usuario_id, fecha, horas_totales, score, sleep_profundo_horas, sleep_rem_horas, sleep_vigilia_horas, despertares) VALUES (28, 1, '2026-04-02', 8.98, 84, 1.32, 1.62, 0.32, 1);
INSERT OR REPLACE INTO datos_sueno (id, usuario_id, fecha, horas_totales, score, sleep_profundo_horas, sleep_rem_horas, sleep_vigilia_horas, despertares) VALUES (29, 1, '2026-04-01', 7.13, 70, 0.82, 0.77, 0.62, 2);
INSERT OR REPLACE INTO datos_sueno (id, usuario_id, fecha, horas_totales, score, sleep_profundo_horas, sleep_rem_horas, sleep_vigilia_horas, despertares) VALUES (30, 1, '2026-03-31', 7.97, 83, 1.82, 1.22, 0.38, 1);
INSERT OR REPLACE INTO datos_sueno (id, usuario_id, fecha, horas_totales, score, sleep_profundo_horas, sleep_rem_horas, sleep_vigilia_horas, despertares) VALUES (31, 1, '2026-03-30', 8.27, NULL, 1.47, 1.53, 0.75, 3);
INSERT OR REPLACE INTO datos_sueno (id, usuario_id, fecha, horas_totales, score, sleep_profundo_horas, sleep_rem_horas, sleep_vigilia_horas, despertares) VALUES (74, 1, '2026-04-06', 9.29, 84, 0.78, 1.92, 0.22, 1);

-- ejercicios_biblioteca (28 rows)
INSERT OR REPLACE INTO ejercicios_biblioteca (id, usuario_id, nombre, grupo_muscular, musculo_principal, tipo, alias, notas, activo, creado_en) VALUES (1, 1, 'Hip Thrust', 'Glúteo', 'Glúteo mayor', 'Fuerza', '["HT","hip thrust"]', NULL, 1, '2026-03-30');
INSERT OR REPLACE INTO ejercicios_biblioteca (id, usuario_id, nombre, grupo_muscular, musculo_principal, tipo, alias, notas, activo, creado_en) VALUES (2, 1, 'Sentadilla búlgara', 'Glúteo', 'Cuádriceps, glúteo', 'Fuerza', '["búlgara","bulgara","split squat"]', NULL, 1, '2026-03-30');
INSERT OR REPLACE INTO ejercicios_biblioteca (id, usuario_id, nombre, grupo_muscular, musculo_principal, tipo, alias, notas, activo, creado_en) VALUES (4, 1, 'Dominadas', 'Espalda', 'Espalda, bíceps', 'Fuerza', '["pull up", "pullup", "dominada"]', NULL, 1, '2026-03-30');
INSERT OR REPLACE INTO ejercicios_biblioteca (id, usuario_id, nombre, grupo_muscular, musculo_principal, tipo, alias, notas, activo, creado_en) VALUES (8, 1, 'Curl femoral', 'Tren inferior', 'Isquiotibial', 'Fuerza', '["femoral","curl femoral","isquio"]', NULL, 0, '2026-03-30');
INSERT OR REPLACE INTO ejercicios_biblioteca (id, usuario_id, nombre, grupo_muscular, musculo_principal, tipo, alias, notas, activo, creado_en) VALUES (9, 1, 'Sentadilla', 'Tren inferior', 'Cuádriceps', 'Fuerza', '["squat","sentadilla libre","sentadillas"]', NULL, 0, '2026-03-30');
INSERT OR REPLACE INTO ejercicios_biblioteca (id, usuario_id, nombre, grupo_muscular, musculo_principal, tipo, alias, notas, activo, creado_en) VALUES (11, 1, 'Abdominales en cable', 'Core', 'Recto abdominal de arriba hacia abajo', 'Fuerza', '["abs en polea", "abs cable", "abdominales polea", "abdominales cable"]', NULL, 1, '2026-03-30');
INSERT OR REPLACE INTO ejercicios_biblioteca (id, usuario_id, nombre, grupo_muscular, musculo_principal, tipo, alias, notas, activo, creado_en) VALUES (12, 1, 'Abdominales colgada', 'Core', 'Recto abdominal de abajo hacia arriba', 'Fuerza', '["abs colgado", "colgadas", "abdominales colgados"]', NULL, 1, '2026-03-30');
INSERT OR REPLACE INTO ejercicios_biblioteca (id, usuario_id, nombre, grupo_muscular, musculo_principal, tipo, alias, notas, activo, creado_en) VALUES (13, 1, 'Press militar', 'Tren superior', 'Hombro', 'Fuerza', '["press hombro","militar","press overhead"]', NULL, 0, '2026-03-30');
INSERT OR REPLACE INTO ejercicios_biblioteca (id, usuario_id, nombre, grupo_muscular, musculo_principal, tipo, alias, notas, activo, creado_en) VALUES (14, 1, 'Plancha', 'Core', 'Core', 'Fuerza', '["plank","plancha abdominal","isométrico"]', NULL, 0, '2026-03-30');
INSERT OR REPLACE INTO ejercicios_biblioteca (id, usuario_id, nombre, grupo_muscular, musculo_principal, tipo, alias, notas, activo, creado_en) VALUES (15, 1, 'Patada en polea', 'Glúteo', NULL, 'Fuerza', '["patada"]', NULL, 0, '2026-04-05');
INSERT OR REPLACE INTO ejercicios_biblioteca (id, usuario_id, nombre, grupo_muscular, musculo_principal, tipo, alias, notas, activo, creado_en) VALUES (16, 1, 'Press de Gemelos', 'Tren inferior', 'Gemelo', 'Fuerza', '["Gemelos", "gemelo"]', NULL, 0, '2026-04-05');
INSERT OR REPLACE INTO ejercicios_biblioteca (id, usuario_id, nombre, grupo_muscular, musculo_principal, tipo, alias, notas, activo, creado_en) VALUES (17, 1, 'Face Pull', 'Hombro', 'Espalda, hombros', 'Fuerza', '["FP", "fp", "face"]', NULL, 1, '2026-04-05');
INSERT OR REPLACE INTO ejercicios_biblioteca (id, usuario_id, nombre, grupo_muscular, musculo_principal, tipo, alias, notas, activo, creado_en) VALUES (18, 1, 'Step Up', 'Glúteo', 'Cuádriceps y glúteo mayor.', 'Fuerza', '["SU"]', NULL, 1, '2026-04-06');
INSERT OR REPLACE INTO ejercicios_biblioteca (id, usuario_id, nombre, grupo_muscular, musculo_principal, tipo, alias, notas, activo, creado_en) VALUES (19, 1, 'Peso Muerto Rumano', 'Tren inferior', 'Isquiotibiales y glúteo mayor.', 'Fuerza', '["rumano", "PM", "Peso muerto"]', NULL, 1, '2026-04-06');
INSERT OR REPLACE INTO ejercicios_biblioteca (id, usuario_id, nombre, grupo_muscular, musculo_principal, tipo, alias, notas, activo, creado_en) VALUES (20, 1, 'Tibia', 'Tren inferior', NULL, 'Fuerza', NULL, NULL, 1, '2026-04-06');
INSERT OR REPLACE INTO ejercicios_biblioteca (id, usuario_id, nombre, grupo_muscular, musculo_principal, tipo, alias, notas, activo, creado_en) VALUES (21, 1, 'Predicador', 'Bíceps', NULL, 'Fuerza', '["Curl concentrado", "Predic"]', NULL, 1, '2026-04-06');
INSERT OR REPLACE INTO ejercicios_biblioteca (id, usuario_id, nombre, grupo_muscular, musculo_principal, tipo, alias, notas, activo, creado_en) VALUES (22, 1, 'Remo abierto', 'Espalda', 'Dorsal ancho, trapecio, romboides y deltoides posterior.', 'Fuerza', '["remo"]', NULL, 1, '2026-04-06');
INSERT OR REPLACE INTO ejercicios_biblioteca (id, usuario_id, nombre, grupo_muscular, musculo_principal, tipo, alias, notas, activo, creado_en) VALUES (23, 1, 'Jalón al Pecho', 'Espalda', 'Dorsal ancho, bíceps braquial y redondo mayor.', 'Fuerza', '["PD", "Pull Down", "jalon", "jal\u00f3n"]', NULL, 1, '2026-04-06');
INSERT OR REPLACE INTO ejercicios_biblioteca (id, usuario_id, nombre, grupo_muscular, musculo_principal, tipo, alias, notas, activo, creado_en) VALUES (24, 1, 'Press Inclinado 30º', 'Hombro', 'Pecho y Hombro Frontal', 'Fuerza', '["press", "PI", "pi", "Press Inclinado"]', NULL, 1, '2026-04-06');
INSERT OR REPLACE INTO ejercicios_biblioteca (id, usuario_id, nombre, grupo_muscular, musculo_principal, tipo, alias, notas, activo, creado_en) VALUES (25, 1, 'Elevaciones laterales', 'Hombro', 'cabeza lateral hombro', 'Fuerza', '["elevaciones", "EL", "el"]', NULL, 1, '2026-04-06');
INSERT OR REPLACE INTO ejercicios_biblioteca (id, usuario_id, nombre, grupo_muscular, musculo_principal, tipo, alias, notas, activo, creado_en) VALUES (27, 1, 'Extensión de tríceps', 'Tríceps', 'cabeza lateral y medial tríceps', 'Fuerza', '["ET", "et"]', NULL, 1, '2026-04-06');
INSERT OR REPLACE INTO ejercicios_biblioteca (id, usuario_id, nombre, grupo_muscular, musculo_principal, tipo, alias, notas, activo, creado_en) VALUES (28, 1, 'Extensiones por encima de la cabeza', 'Tríceps', 'cabeza larga del tríceps', 'Fuerza', '["extensi\u00f3n cabeza", "extension cabeza", "cabeza triceps", "CT", "ct"]', NULL, 1, '2026-04-06');
INSERT OR REPLACE INTO ejercicios_biblioteca (id, usuario_id, nombre, grupo_muscular, musculo_principal, tipo, alias, notas, activo, creado_en) VALUES (29, 1, 'Curl de bíceps en banco inclinado 60º', 'Bíceps', 'cabeza larga del bíceps', 'Fuerza', '["curl inclinado", "Curl banco"]', NULL, 1, '2026-04-06');
INSERT OR REPLACE INTO ejercicios_biblioteca (id, usuario_id, nombre, grupo_muscular, musculo_principal, tipo, alias, notas, activo, creado_en) VALUES (30, 1, 'Curl Martillo en polea', 'Bíceps', 'cabeza corta del bíceps, el braquial anterior y el braquiorradial', 'Fuerza', '["Curl Martillo"]', NULL, 1, '2026-04-06');
INSERT OR REPLACE INTO ejercicios_biblioteca (id, usuario_id, nombre, grupo_muscular, musculo_principal, tipo, alias, notas, activo, creado_en) VALUES (31, 1, 'Press Pallof en polea', 'Core', 'Oblicuos (Laterales y rotación)', 'Fuerza', '["press abs", "pallof"]', NULL, 1, '2026-04-06');
INSERT OR REPLACE INTO ejercicios_biblioteca (id, usuario_id, nombre, grupo_muscular, musculo_principal, tipo, alias, notas, activo, creado_en) VALUES (32, 1, 'Rueda Abdominal', 'Core', 'Transverso y Estabilidad profunda', 'Fuerza', '["rueda"]', NULL, 1, '2026-04-06');
INSERT OR REPLACE INTO ejercicios_biblioteca (id, usuario_id, nombre, grupo_muscular, musculo_principal, tipo, alias, notas, activo, creado_en) VALUES (33, 1, 'Abducciones en polea', 'Glúteo', 'Glúteo Medio y Mínimo', 'Fuerza', '["abducciones"]', NULL, 1, '2026-04-06');
INSERT OR REPLACE INTO ejercicios_biblioteca (id, usuario_id, nombre, grupo_muscular, musculo_principal, tipo, alias, notas, activo, creado_en) VALUES (34, 1, 'Gemelo de pie', 'Tren inferior', 'gastrocnemio y el sóleo.', 'Fuerza', '["gemelo"]', NULL, 1, '2026-04-06');

-- historial_ejercicio (13 rows)
INSERT OR REPLACE INTO historial_ejercicio (id, ejercicio_id, usuario_id, fecha, peso, series, repeticiones, rpe, notas) VALUES (1, 1, 1, '2026-03-31', 30.0, 3, 8, 6, '');
INSERT OR REPLACE INTO historial_ejercicio (id, ejercicio_id, usuario_id, fecha, peso, series, repeticiones, rpe, notas) VALUES (2, 2, 1, '2026-03-31', 14.0, 3, 8, 6, '');
INSERT OR REPLACE INTO historial_ejercicio (id, ejercicio_id, usuario_id, fecha, peso, series, repeticiones, rpe, notas) VALUES (3, 4, 1, '2026-03-30', 0.0, 3, 8, 6, '');
INSERT OR REPLACE INTO historial_ejercicio (id, ejercicio_id, usuario_id, fecha, peso, series, repeticiones, rpe, notas) VALUES (4, 22, 1, '2026-03-30', 27.0, 3, 8, 6, 'sin terminar');
INSERT OR REPLACE INTO historial_ejercicio (id, ejercicio_id, usuario_id, fecha, peso, series, repeticiones, rpe, notas) VALUES (5, 11, 1, '2026-03-30', 45.0, 3, 8, 6, '');
INSERT OR REPLACE INTO historial_ejercicio (id, ejercicio_id, usuario_id, fecha, peso, series, repeticiones, rpe, notas) VALUES (6, 30, 1, '2026-03-30', 27.0, 3, 6, 6, '');
INSERT OR REPLACE INTO historial_ejercicio (id, ejercicio_id, usuario_id, fecha, peso, series, repeticiones, rpe, notas) VALUES (7, 12, 1, '2026-03-30', 0.0, 3, 6, 6, '');
INSERT OR REPLACE INTO historial_ejercicio (id, ejercicio_id, usuario_id, fecha, peso, series, repeticiones, rpe, notas) VALUES (8, 4, 1, '2026-03-30', 0.0, 3, 8, 6, 'sola 2 asistidas');
INSERT OR REPLACE INTO historial_ejercicio (id, ejercicio_id, usuario_id, fecha, peso, series, repeticiones, rpe, notas) VALUES (9, 4, 1, '2026-03-27', 0.0, 3, 8, 6, '');
INSERT OR REPLACE INTO historial_ejercicio (id, ejercicio_id, usuario_id, fecha, peso, series, repeticiones, rpe, notas) VALUES (10, 22, 1, '2026-03-27', 27.0, 3, 8, 6, 'sin terminar');
INSERT OR REPLACE INTO historial_ejercicio (id, ejercicio_id, usuario_id, fecha, peso, series, repeticiones, rpe, notas) VALUES (11, 11, 1, '2026-03-27', 45.0, 3, 8, 6, '');
INSERT OR REPLACE INTO historial_ejercicio (id, ejercicio_id, usuario_id, fecha, peso, series, repeticiones, rpe, notas) VALUES (12, 30, 1, '2026-03-27', 27.0, 3, 6, 6, '');
INSERT OR REPLACE INTO historial_ejercicio (id, ejercicio_id, usuario_id, fecha, peso, series, repeticiones, rpe, notas) VALUES (13, 12, 1, '2026-03-27', 0.0, 3, 6, 6, '');

-- ejercicios_por_defecto (2 rows)
INSERT OR REPLACE INTO ejercicios_por_defecto (id, usuario_id, ejercicio, grupo_muscular, musculo_principal) VALUES (1, 1, 'Hip Trust', 'Tren Inferior', 'Glúteo');
INSERT OR REPLACE INTO ejercicios_por_defecto (id, usuario_id, ejercicio, grupo_muscular, musculo_principal) VALUES (2, 1, 'dominadas', 'Tren Superior', 'lats');

-- lesiones (2 rows)
INSERT OR REPLACE INTO lesiones (id, usuario_id, tipo, grado, fecha_inicio, fecha_fin, activa, notas) VALUES (1, 1, 'Periostitis', 1, '2026-04-05', '2026-04-05', 0, NULL);
INSERT OR REPLACE INTO lesiones (id, usuario_id, tipo, grado, fecha_inicio, fecha_fin, activa, notas) VALUES (2, 1, 'Periostitis', 1, '2026-04-05', '2026-04-05', 0, NULL);
