[theme]
primaryColor = "#C9FF00"
backgroundColor = "#0D1117"
secondaryBackgroundColor = "#161B22"
textColor = "#C9E1FF"
font = "sans serif"

[client]
showErrorDetails = false

[logger]
level = "error"

[browser]
gatherUsageStats = false
